### ISSUE TITLE
Training and testing dataset

### ISSUE THREAD

**Issue by cuongnc220592** [junqiangchen/TN-SCUI2020-Challenge#1]
Hi author,

Could you provide the original dataset.
I do not have the permission to download it on the website
https://tn-scui2020.grand-challenge.org/Source_links/

Thank you very much

**Comment by junqiangchen** [comment]
> Hi author,
> 
> Could you provide the original dataset.
> I do not have the permission to download it on the website
> https://tn-scui2020.grand-challenge.org/Source_links/
> 
> Thank you very much

Hi，the source dataset can't download from website，can't share with anyone at same time.
thank you
